{"links": {"self": {"href": "data/repositories/philipstarkey/qtutils/issues/1/comments/42800932.json"}, "html": {"href": "#!/philipstarkey/qtutils/issues/1#comment-42800932"}}, "issue": {"links": {"self": {"href": "data/repositories/philipstarkey/qtutils/issues/1.json"}}, "type": "issue", "id": 1, "repository": {"links": {"self": {"href": "data/repositories/philipstarkey/qtutils.json"}, "html": {"href": "#!/philipstarkey/qtutils"}, "avatar": {"href": "data/bytebucket.org/ravatar/{eb85b0e6-11dc-449a-96ec-21935a03d721}ts=python"}}, "type": "repository", "name": "qtutils", "full_name": "philipstarkey/qtutils", "uuid": "{eb85b0e6-11dc-449a-96ec-21935a03d721}"}, "title": "invoke_in_main leaks memory when using PySide"}, "content": {"raw": "Despite this being reported as resolved, they haven't actually released a version of PySide with the bug fix in (there's been no release since 2015). So I think I'll leave this open until they do!", "markup": "markdown", "html": "<p>Despite this being reported as resolved, they haven't actually released a version of PySide with the bug fix in (there's been no release since 2015). So I think I'll leave this open until they do!</p>", "type": "rendered"}, "created_on": "2018-01-23T03:26:39.938764+00:00", "user": {"display_name": "Philip Starkey", "uuid": "{48af65db-e5fc-459c-a7eb-52eb1f9a5690}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D"}, "html": {"href": "https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/dc318537facc47ebe1ae98a7aabacecfd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPS-0.png"}}, "nickname": "pstarkey", "type": "user", "account_id": "557058:52a111e4-40da-4441-9143-417f95f2db97"}, "updated_on": null, "type": "issue_comment", "id": 42800932}